[package]
name = "ppppp-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
futures = "0.3.29"
serde = "1.0.193"

[[example]]
name = "ping"
