[package]
name = "ppppp-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
futures-core = "0.3.29"
tokio = "1.33.0"
tokio-stream = "0.1.14"
